---
- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Log in to Docker Hub
      echo "{{ lookup('env', 'DOCKER_PASSWORD') }}" | docker login -u "{{ lookup('env', 'DOCKER_USERNAME') }}" --password-stdin
      env:
        DOCKER_USERNAME: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        DOCKER_PASSWORD: "{{ lookup('env', 'DOCKER_PASSWORD') }}" 
    - name: Run Docker container
      docker_container:
        name: banking and finance app
        image: nikitaks997797/capstone_project1:$BUILD_NUMBER
        state: started
        ports:
          - "8080:8081" 
