---
- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: python3-pip
        state: present
    - name: Log in to Docker Hub
      shell: |
       pip install docker
       echo "{{ lookup('env', 'DOCKER_PASSWORD') }}" | docker login -u "{{ lookup('env', 'DOCKER_USERNAME') }}" --password-stdin
    - name: Run Docker container
      docker_container:
        name: bank_app
        image: nikitaks997797/capstone_project1:2
        state: started
        ports:
          - "8080:8081" 
